version: "3"
services:
  app:
    build: .
    links:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DP_TYPE=${DP_TYPE}
      - DP_HOST=${DP_HOST}
      - DP_PORT=${DP_PORT}
      - DP_USERNAME=${DP_USERNAME}
      - DP_PASSWORD=${DP_PASSWORD}
      - DP_DATABASE=${DP_DATABASE}
      - DP_SYNCHRONIZE=${DP_SYNCHRONIZE}
      - DP_LOGGING=${DP_LOGGING}
      - JWT_SECRET=${JWT_SECRET}
      - SALT_ROUND=${SALT_ROUND}
    command: npm run start

  postgres:
    image: postgres:11.5
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

